version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: api:v1
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
    networks:
      - backend

networks:
  backend:
    driver: bridge
